### ISSUE TITLE
"Twin Long Rods #1" and "Twin Long Rods #2" images are reversed

### ISSUE THREAD

**Issue by BeyondTheHorizon** [shadowfox87/YGOTCGOCGHQPics#17]
I noticed that the images for "Twin Long Rods #1" and "Twin Long Rods #2" are reversed when opened in DataEditorX i.e. clicking on "Twin Long Rods #1" yields the image for "Twin Long Rods #2" and vice-versa. This could easily be changed by reversing their current IDs, but I thought I'd bring it up anyway.

**Comment by jacmaz** [comment]
Thank you! it is fixed now.
